version: '2'

services:
  jenkins-master:
    build: infrastructure/jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  jenkins-slave:
    restart: always
    build: infrastructure/jenkins-slave
    privileged: true
    volumes:
      - jenkins_slave_home:/var/jenkins_home
    environment:
      - JENKINS_URL=http://jenkins-master:8080 a46976cf3bee66895b978c7243a624bb08540535e00435072dad3004679ae3eb slave1
volumes:
  jenkins_home:
    driver: local
  jenkins_slave_home:
    driver: local
